Adding AutoRole feature
SlamaFR/UGE-Bot pull request #1
Opened 2021-06-10 17:29 UTC by SlamaFR

Changes :
- Command to create AutoRole
- Automatic restore at startup

Upcoming changes :
- Role limit check
- Emote on buttons
- Autocompletion on command

2021-06-10 18:06 UTC, notKamui requested changes
Pretty good PR ; a lot of bang bang operators that need to be removed ; it takes time to get used to, and it might even seem clunky. Keep in mind that it'll really avoid a lot of bugs. Kotlin is not always "shorter java"

2021-06-10 18:06 UTC, notKamui commented on src/main/kotlin/main.kt
> +        jda.addEventListener(AutoRoleCommand())
addEventListener supports varargs, so you should use this syntax

```
jda.addEvenListener(
    Command1(),
    Command2()
)
```

2021-06-10 18:06 UTC, notKamui commented on src/main/kotlin/events/autoroles.kt
> +val logger: Logger = LoggerFactory.getLogger("AutoRolesManager")
Type is explicit enough, you should remove it as per Ktlint's guidelines

2021-06-10 18:06 UTC, notKamui commented on src/main/kotlin/events/autoroles.kt
> +val autoRoles: MutableMap<Long, MutableMap<String, AutoRole>> = mutableMapOf()
Remove explicit type and move it over on the right side, as a type param of mutableMapOf()

2021-06-10 18:06 UTC, notKamui commented on src/main/kotlin/events/autoroles.kt
> +    if (name !in autoRoles[guild.idLong]!!.keys) {
Never use !! outside of tests. Instead, keep autoRoles[guild.idLong] in a `val` beforehand and assert that it is not null. You can throw a proper exception if that happens to be the case. You should never assume the JVM will never have memory issues, thus, you can supposedly never be sure 100% something is not null.

2021-06-10 18:06 UTC, notKamui commented on src/main/kotlin/events/autoroles.kt
> +    config.autoRoles.forEach {
`it` should be explicited here. You can keep as a guideline that if you iterate over anything other than a List or an Array (e.g. a Map), you should rename `it`. That is also to be considered if the name of the list isn't something like a plural noun (e.g. `persons` -> for each person -> `it` is obvious here)

In the case of a map, you can use destructuring to rename `it.key` and `it.value` completely.

`config.autoRoles.forEach { (name, role) -> ...`

2021-06-10 18:06 UTC, notKamui commented on src/main/kotlin/events/autoroles.kt
> +        val role = event.guild!!.getRoleById(roles[index])
No !!, cf same issue higher

2021-06-10 18:06 UTC, notKamui commented on src/main/kotlin/events/autoroles.kt
> +        if (role in event.member!!.roles) return
No !!, cf same issue higher

2021-06-10 18:06 UTC, notKamui commented on src/main/kotlin/events/autoroles.kt
> +        event.guild!!.addRoleToMember(event.user.id, role).queue() {
No !!, cf same issue higher

2021-06-10 18:06 UTC, notKamui commented on src/main/kotlin/core/config.kt
> +        Json.decodeFromString(File("config/guilds/${guildId}/roles.json").readText()),
Might be a good idea to keep "config/guilds/" in a private const val ; we may need to change the location in the future

2021-06-10 18:06 UTC, notKamui commented on src/main/kotlin/commands/call_command.kt
> +    private val uniqueId = event.member!!.id + System.currentTimeMillis().toString()
No !!, cf. same issue in autoroles.kt ; use `let`

```kt
private val uniqueId = event.member?.let { it.id + System.currentTimeMillis().toString() } ?: ""
```

2021-06-10 18:06 UTC, notKamui commented on src/main/kotlin/commands/autorole_command.kt
> +        val autoRole = createAutoRoleIfAbsent(event.guild!!, event.getOption("name")!!.asString)
No !!, cf. same issue in autoroles.kt

2021-06-10 18:06 UTC, notKamui commented on src/main/kotlin/commands/autorole_command.kt
> +                "**Erreur :** l'attributeur `${event.getOption("name")!!.asString}` n'existe pas. " +
No !!, cf. same issue in autoroles.kt

2021-06-10 18:12 UTC, SlamaFR commented on src/main/kotlin/commands/call_command.kt
> +    private val uniqueId = event.member!!.id + System.currentTimeMillis().toString()
We can't use Elvis operator here, we absolutely need a unique ID based on requester.

2021-06-10 18:56 UTC, notKamui commented on src/main/kotlin/commands/call_command.kt
> +    private val uniqueId = event.member!!.id + System.currentTimeMillis().toString()
It's better to throw an exception then (that is not an NPE ofc) ; you can throw it after the Elvis. Else you can do something like that maybe:

```kt
private val uniqueId = (event.member?.id ?: "00000000000000") + System.currentTimeMillis().toString()
```

2021-06-10 20:55 UTC, SlamaFR commented on src/main/kotlin/main.kt
> +        jda.addEventListener(AutoRoleCommand())
Indeed, I should use varargs syntax but this is somehow temporary. We'll come up with a robust and smart system to register commands listeners programmatically.

2021-06-10 20:59 UTC, notKamui commented on src/main/kotlin/main.kt
> +        jda.addEventListener(AutoRoleCommand())
Sure thing ; I'll let you do it anyway so that it's still consistent with the current master branch

2021-06-10 21:01 UTC, notKamui commented on src/main/kotlin/events/autoroles.kt
> +val autoRoles: MutableMap<Long, MutableMap<String, AutoRole>> = mutableMapOf()
(we generally want types the furthest possible to the right)

2021-06-10 21:02 UTC, SlamaFR commented on src/main/kotlin/commands/autorole_command.kt
> +        val autoRole = createAutoRoleIfAbsent(event.guild!!, event.getOption("name")!!.asString)
Well, since the option if flagged required, technically it is impossible to have it `null` here. But, I'll add a check just in case.

2021-06-11 23:02 UTC, SlamaFR commented on src/main/kotlin/events/autoroles.kt
> +val logger: Logger = LoggerFactory.getLogger("AutoRolesManager")
Well, actually IntelliJ suggests me to keep explicit type.

![image](https://user-images.githubusercontent.com/13136802/121756281-d601df80-cb19-11eb-8c9c-cf2695678308.png)

2021-06-11 23:09 UTC, notKamui commented on src/main/kotlin/events/autoroles.kt
> +val logger: Logger = LoggerFactory.getLogger("AutoRolesManager")
Oh, noted ; to expand on this, the reason here is not for clarity but subduing a platform type. A platform type is usually noted Type! (as opposed to Type or Type?). It's in fact just a concept, generally due to the fact that Java types are not explicit. In this case, you enforce that type to erase the platform type.

2021-06-11 23:19 UTC, SlamaFR commented on src/main/kotlin/commands/call_command.kt
> +    private val uniqueId = event.member!!.id + System.currentTimeMillis().toString()
Will change `member` to `user` to fix the issue and keep uniqueness of ID.

2021-06-11 23:44 UTC, SlamaFR commented on src/main/kotlin/events/autoroles.kt
> +val logger: Logger = LoggerFactory.getLogger("AutoRolesManager")
So can it stay as it is?

2021-06-12 08:27 UTC, notKamui commented on src/main/kotlin/events/autoroles.kt
> +val logger: Logger = LoggerFactory.getLogger("AutoRolesManager")
yeah sure

2021-06-12 08:38 UTC, notKamui requested changes

2021-06-12 08:38 UTC, notKamui commented on src/main/kotlin/commands/autorole_command.kt
> +        val autoRole = createAutoRoleIfAbsent(event.guild!!, name.asString)
You can and should use let here

```kt
 val autoRole = even.guild?.let { guild -> createAutoRoleIfAbsent(guild, name.asString) }
 ```

As a guideline, you can use let instead of declaring a var and asserting it's not null ONLY when you have to use an object as not-null once or several times in instructions following each other (or separated by very few other instructions)

2021-06-12 08:38 UTC, notKamui commented on src/main/kotlin/events/autoroles.kt
> +        if (role == null) {
You should put that if and its scope above the if just above (semantics: it's more logical to check if a role exists before checking if a user already has it)

2021-06-12 09:32 UTC, notKamui approved these changes
Seems good to me, merge approved.

2021-06-12 09:44 UTC, merged