Feature: delete command
SlamaFR/UGE-Bot pull request #7
Opened 2021-06-13 18:32 UTC by notKamui

There is now two new server-side commands:
- `delete-commands <name1> ... <nameN>`
- `delete-glocal-commands <name1> ... <nameN>`

As their names suggest, they serve to delete guild and global commands by names. (Take into account that it will take about an hour to delete a global command)

2021-06-13 20:46 UTC, SlamaFR requested changes
Good PR. I pointed out a spot subject to improvement. What do you think?

2021-06-13 20:46 UTC, SlamaFR commented on src/main/kotlin/main.kt
> +        }
I see what you did there. This code is actually working but is not very clean. I suggest you should use `Guild#retrieveCommands()` which is a `RestAction` to get all registered commands as a list.

This way, if the command is not found, you save a useless request to API.
Same for right below with `JDA#retrieveCommands()`

2021-06-13 22:13 UTC, notKamui commented on src/main/kotlin/main.kt
> +        }
Definitely ! I didn't know about this method (even though I did search for it). Gonna fix this up soon.

2021-06-14 13:38 UTC, SlamaFR approved these changes

2021-06-14 14:27 UTC, merged