Add ability to call by a given role to gather missing students
SlamaFR/UGE-Bot pull request #81
Opened 2022-01-12 14:54 UTC by SlamaFR

Teachers can now initiate calls with a given role to retrieve missing students.

Resolves #80

2022-01-12 15:03 UTC, notKamui requested changes

2022-01-12 15:03 UTC, notKamui commented on src/main/kotlin/io/slama/commands/call_command.kt
> +        role?.run {
Replace with if (role != null)

2022-01-12 15:03 UTC, notKamui commented on src/main/kotlin/io/slama/commands/call_command.kt
> +                role?.let {
Replace with if not null

2022-01-12 15:10 UTC, notKamui approved these changes

2022-01-12 15:14 UTC, merged

2022-01-13 10:26 UTC, SlamaFR commented
Accidentally merged this into `master`. Fixed this by force-merging into a a new branch `version/2.1.2`